#### Python Day Three Task
##### (If-Else , While Loop , For loop, Function)

In [24]:
#If-Else Statment
a = 20
b = 30
if b > a:
    print('b is greater than a')

a = 100 
b = 20
if b < a:
    print('a is greater')
else:
    print('b  is greater')

a = 33
b = 33

if b > a:
    print('b is greater than a')
elif a == b:
    print('a and b are equal')
else:
    print('a is greater')

#short Hand if/if_else:
a = 100 
b = 50
if a > b : print('a is greater than b')

a = 50 
b = 60
print('A') if a > b else print('B')

a = 400
b = 400
print('A') if a > b else print ('=') if a == b else print('B') 

#And/Or/Not
a = 100
b = 50 
c = 200
if a > b & b < c:
    print('Condition are true')
else:
    print('condition is not true')

a = 500
b = 100
c = 50 
if a > b or c < b:
    print('Or condition is true')

a = 40
b = 200

if not a > b:
    print('a is not greater than b')

#Nested if 
a = 41

if a > 40:
    print('Above 40')
if a > 22:
    print('also Above 22')
else:
    print('but not above 43')

b is greater than a
a is greater
a and b are equal
a is greater than b
B
=
Condition are true
Or condition is true
a is not greater than b
Above 40
also Above 22

In [42]:
#While loop
i = 1
while i < 6:
    print(i)
    i += 1

i = 2
while i < 10:
    print(i)
    if (i == 8):
        break
    i += 1

i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)
   

i = 1
while i < 6:
    print(i)
    i += 1
else:
    print('i is no longer less than 6')

1
2
3
4
5
2
3
4
5
6
7
8
1
2
4
5
6
1
2
3
4
5
i is no longer less than 6

In [23]:
#For loop
fruits = ['apple','mango','banana']
for fruit in fruits:
    print(fruit)

for words in "banana":
    print(words)

fruits = ['apple','orange','mango','kiwi']
for fruit in fruits :
    print(fruit)
    if fruit == 'mango':
        break

fruits = ['apple','orange','mango','kiwi']
for fruit in fruits:
    if fruit == 'orange':
        break
    print(fruit)

fruits = ['apple','orange','mango','kiwi']
for fruit in fruits[0:2]:
    print(fruit)

for x in range (0,40,4):
    print(x)

for x in range(6):
    print(x)
else:
    print('Finished')

for x in range(7):
    if x == 5: break
    print(x)
else:
    print('Finally Finished')

color = ['red','yellow','green']
fruits = ['apple','mango','banana']
for colors in color:
    for fruit in fruits:
        print(colors,fruit)

apple
mango
banana
b
a
n
a
n
a
apple
orange
mango
apple
apple
orange
0
4
8
12
16
20
24
28
32
36
0
1
2
3
4
5
Finished
0
1
2
3
4
red apple
red mango
red banana
yellow apple
yellow mango
yellow banana
green apple
green mango
green banana

In [58]:
#Functions
def my_function():
    print('Hello this is my first function')
my_function() 

def my_function(fname):
    print(fname + 'Refsnes')

my_function('Email')
my_function('laptop')
my_function('Linus')

def my_function(fname,lname,surname):
    print(fname + ' ' + lname + surname)
my_function('Ahsan','Refsens','old')

#arbitary arguments
def my_function(*kids):
    print('The youngest kid is ' + kids[2])
my_function('Ahsan','Ali','Zeeshan')

def my_function(child3,child2,child1):
    print('The smallest kid is '+ child2)
my_function(child1='ALi',child3='Zeeshan',child2='Ahmed')


def my_function(country = 'Pakistan'):
    print('I am from '+ country)
my_function('India')
my_function()
my_function('England')
my_function('Austria')

def my_function(food):
    for x in food:
        print(x)
fruits = ['apple','mango','orange']
my_function(fruits)

def my_function(x):
    return 5 * x
print(my_function(3))
print(my_function(5))
print(my_function(10))

def my_function(a,b,/,*,c,d):
    print(a + b + c + d)

my_function (4,7, c = 7, d = 10)


#Exercise
def happy_birthday(name,age):
    print(f'Happy Birthday to {name}')
    print(f'You are {age} years old!')

happy_birthday('Ahsan',24)
happy_birthday('Ali',25)

#Exercise 2
def display_invoice(name,billinvoice,duedate):
    print(f"Hello {name}")
    print(f"your bill invoice is {billinvoice} $ due date is : {duedate} ")

display_invoice('Ahsan',230,'28/09')

#Exercise 3
def create_name (first,last):
    first = first.capitalize()
    last = last.capitalize()
    return first + ' ' + last

full_name =create_name ('Ahsan','ijaz')
print(full_name)

Hello this is my first function
EmailRefsnes
laptopRefsnes
LinusRefsnes
Ahsan Refsensold
The youngest kid is Zeeshan
The smallest kid is Ahmed
I am from India
I am from Pakistan
I am from England
I am from Austria
apple
mango
orange
15
25
50
28
Happy Birthday to Ahsan
You are 24 years old!
Happy Birthday to Ali
You are 25 years old!
Hello Ahsan
your bill invoice is 230 $ due date is : 28/09
Ahsan Ijaz

In [49]:
#lambda
x = lambda a : a + 10 
print(x(5))

x = lambda a , b : a * b
print(x(10,4))

x = lambda a,b,c : a * b * c
print(x(5,10,6))

def myfunc(n):
    return lambda a : a*n

mydoubler =  myfunc(4)
print(mydoubler(10))


def my_function(n):
    return lambda a: a * n

mytripler = my_function(3)
print(mytripler(5))


def my_function(n):
    return lambda a: a *n

mydoubler = my_function(2)
mytripler = my_function(3)

print(mydoubler(5))
print(mytripler(6))

15
40
300
40
15
10
18

In [ ]:
#Arrays